[package]
name = "json_to_csv_converter"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.26.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
csv = "1.3"
rfd = "0.12"
anyhow = "1.0"
